services:
  db:
    image: postgres:16-alpine
    container_name: restaurant_app_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: restaurant_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
